### PR TITLE
Adding spanish translations

### LINKED ISSUE #90: Translate the app in Spanish
* [store-listing](https://github.com/openwebnet/openwebnet-android/tree/master/store-listing)
* [strings.xml](https://github.com/openwebnet/openwebnet-android/blob/master/app/src/main/res/values/strings.xml)

### PR DESCRIPTION
**Pull request by Ullauri**
closes #90.

### CODE REVIEW

**Comment by niqdev** [comment]
@Ullauri thanks a lot for your contribution!
I'll hold this until I finish the development on the backup, I have few versions in beta already and if you are still available I'll ask you to translate a bunch of more labels.

**Comment by Ullauri** [comment]
Sounds good.

**Comment by niqdev** [comment]
@Ullauri I've just released version `3.2.0` with lots of changes, could you please review the following files

* [strings.xml](https://github.com/openwebnet/openwebnet-android/blob/master/app/src/main/res/values/strings.xml)
* [store-listing](https://github.com/openwebnet/openwebnet-android/tree/master/store-listing)
* [changelog.xml](https://github.com/openwebnet/openwebnet-android/blob/master/app/src/main/res/raw-it/changelog.xml) (add raw-es)

As soon as you update them, I'll merge the PR.

Thanks a lot!

**Comment by Ullauri** [comment]
sounds good, I'll try and get this done sometime this week =)

**Comment by niqdev** [comment]
Hi @Ullauri, sorry for bothering you, is there any progress on this?
Several strings have been added and changed since you opened the PR and I'd like to merge it.
Thanks!

**Pull request closed without merging**
